//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Task
    {
        [DataMember(Name = "taskID")]
        public int Task_ID { get; set; }

        [DataMember(Name = "taskName")]
        public string TaskName { get; set; }

        [DataMember(Name = "parentID")]
        public Nullable<int> Parent_ID { get; set; }

        [DataMember(Name = "projectID")]
        public Nullable<int> Project_ID { get; set; }

        [DataMember(Name = "startDate")]
        public Nullable<System.DateTime> Start_Date { get; set; }

        [DataMember(Name = "endDate")]
        public Nullable<System.DateTime> End_Date { get; set; }

        [DataMember(Name = "priority")]
        public Nullable<int> Priority { get; set; }

        [DataMember(Name = "status")]
        public string Status { get; set; }        
    }
}
